services:
  web:
    build: .
    image: moji-chat-server-app
    restart: unless-stopped
    env_file: .env
    ports:
      - $PORT:$PORT
  
  redis:
    image: redis
    container_name: redis
    env_file: .env
    ports:
      - $RDB_PORT:6379
    # if you need a password to using the redis please unlock this comment
    # command: redis-server --requirepass $RDB_PASSWORD

  postgres:
    image: postgres
    container_name: postgres
    env_file: .env
    ports:
      - $DB_POSTGRESS_PORT:5432
    environment:
      - POSTGRES_PASSWORD=$DB_POSTGRESS_PASS
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata: 
    driver: local
    driver_opts:
      type: none
      device: /Users/clover/dev-project/docker
      o: bind
