services:
  web:
    build: .
    image: moji-chat-server-app
    restart: unless-stopped
    env_file: .env
    ports:
      - "$PORT:$PORT"

  postgres:
    image: postgres
    container_name: postgres
    env_file: .env
    ports:
      - "$DB_POSTGRESS_PORT:$DB_POSTGRESS_PORT"
    environment:
      - POSTGRES_PASSWORD=$DB_POSTGRESS_PASS
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
